httpClientService:
  connectionRequestTimeout: 5000
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 1000
  automaticRetries: false
  closeTask:
    idleTime: 5000
    delay: 5000
config:
  route: "https://api.github.com/repos/shy526/dev-env-arrange-repo/contents/route"
  env: "D:/codeup/dev-env-arrange/src/test/resources"
  routeCache: "D:/codeup/dev-env-arrange/src/test/resources/cache"
spring:
  shell:
    command:
      history:
        enabled: false
      script:
        enabled: false