httpClientService:
  connectionRequestTimeout: 500
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  automaticRetries: false
  closeTask:
    idleTime: 4000
    delay: 4000
config:
  route: "D:/个人文件/桌面/test111"
spring:
  shell:
    command:
      history:
        enabled: false
      script:
        enabled: false